### ISSUE TITLE
Setup a performance test suite

### ISSUE THREAD

**Issue by crismali** [devmynd/jsonb_accessor#15] opened 2015-04-08 15:01 UTC
This gem does a lot of metaprogramming by adding methods and scopes to a base ActiveRecord model. 

The goal of this suite would be to test the amount of overhead added to base ActiveRecord as we add more features. 

Not critical, but would be nice to have as an objective yardstick.

**Comment by blizkreeg** [comment] 2016-03-30 23:01
I really think we need a performance test suite. I am using jsonb_accessor and am finding my AR object instantiation is dog slow (over 10x slower). I love the functionality but I've had to rip it out due to the performance.

**Comment by jhirn** [comment] 2016-04-11 19:01
Hey @blizkreeg. If you could provide the specific use case that would be great. We're currently looking at implementing #36 and #37 as well as a bigger change which came from investigation on #30. If you could provide a base case for us to test before and after it would be helpful.

**Comment by blizkreeg** [comment] 2016-04-11 19:09
hey @jhirn, PR https://github.com/devmynd/jsonb_accessor/pull/37 was exactly my finding and I was going to open a similar PR myself. The base case is really simple - a model with a dozen or so attributes. Instantiate/find a model. When you're reading dozens or hundreds of records from the database, this instantiation from db is the biggest hit. Each individual object instantiation takes up to 300-400ms, which is just extremely slow. A huge part of it is spend in the type lookup code fixed in the PR above.

**Comment by haruska** [comment] 2016-04-11 21:45
@blizkreeg have a look at #44. Running that test against #37 shows no improvement in run time. In fact it is a bit slower, but still 2 orders magnitude.

Just curious if you were thinking of something else for your PR or if something like #37 speeds up some other slow aspect of jsonb_accessor.

**Comment by haruska** [comment] 2016-04-11 22:16
There is now the beginning of a performance test suite in master, along with a simple test that should be greatly improved.

I'm closing this issue (as it is now setup) but work remains to actually speed up jsonb_accessor.

**Closed by haruska** 2016-04-11 22:16 UTC
Labels: enhancement

**Comment by justin808** [comment] 2018-10-03 04:18
I can confirm that this gem added a huge overhead to queries on a model containing many jsonb fields. We had to rip out the gem and replace with a bit of our own code.
