### ISSUE TITLE
warning: already initialized constant JsonbAccessor::JAPerson::JAExtras

### ISSUE THREAD

**Issue by imton** [devmynd/jsonb_accessor#26] opened 2015-07-20 17:28 UTC
Hi! This gem is awesome!

I am getting, any idea?

````
/Users/gaston/.rvm/gems/ruby-2.2.1/gems/jsonb_accessor-0.3.0/lib/jsonb_accessor/class_builder.rb:40: warning: already initialized constant JsonbAccessor::JAPerson::JAExtras

/Users/gaston/.rvm/gems/ruby-2.2.1/gems/jsonb_accessor-0.3.0/lib/jsonb_accessor/class_builder.rb:40: warning: previous definition of JAExtras was here
````

**Comment by crismali** [comment] 2015-07-20 21:24
This could be caused by having 2 nested fields that are both named `extras` like this: 

```ruby
class Foo < ActiveRecord::Base
  jsonb_accessor :jsonb_column_1, extras: { nested: :value }
  jsonb_accessor :jsonb_column_2, extras: { nested: :value }
end
```

**Comment by imton** [comment] 2015-07-20 21:31
Mmm I was using jsonb_accessor along side with store_accessor, was that?

**Comment by crismali** [comment] 2015-07-20 21:33
I don't think so. Could you provide an example of the code that is causing this problem?

**Comment by crismali** [comment] 2015-07-27 18:15
@imton Just checking in. A complete example would really help us diagnose this.

**Comment by hachpai** [comment] 2015-08-26 14:02
I had the same, but it was because I had miswritten the jsonb column name.

**Comment by crismali** [comment] 2015-10-22 14:05
Closing this until a more detailed example is available.

**Closed by crismali** 2015-10-22 14:05 UTC
Labels: question
